### ISSUE TITLE
Implement `codelyze/patch` commit status

### ISSUE THREAD

**Issue by megheaiulian** [codelyze/action#196]
implement a `codelyze/patch` commit status that displays the ratio of lines covered in the commit/patch or PR.

To implement this you need to follow this algorithm:
1. Get all the lines added
2. Filter out the added lines in files that are not included in the lcov.
3. Get the ratio by calculated how may of them are hit by the lcov

After getting the ratio we need to add a commit status: 
`codelyze/patch - 100.00% of diff hit`

https://octokit.github.io/rest.js/v20/

**Comment by ymcorrea** [comment]
Hello!
I want to work in your organization as a fullstack developer
If you are okay, could you give me a chance to work with you?

**Comment by megheaiulian** [comment]
by #235 235
